global:
  scrape_interval: 10s
scrape_configs:
  - job_name: 'worldcheck'
    static_configs:
      - targets: ['worldcheck:8080']
  - job_name: 'attestor'
    static_configs:
      - targets: ['attestor:8080']
  - job_name: 'control'
    static_configs:
      - targets: ['control:8080']
